apiVersion: v1
meta-data:
  name: react-typescript-data-gen
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEEwTURFdwpPVEUyTkRaYUZ3MDBNVEEwTURFd09URTJORFphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEYmhCN1JWN3NVRXBIU2RpM3ErWm5nWitNb0kraEJ6bU5jbGo4UVRoM0hmd3FCZktXbQpLWExJdXFGZjcyVlQ3MUNhbUZIY1dzSk9JTTVhRlpYYW11VXY1WVMvYWM3ekQwQzM5dDhQMlN4WFBwYTBMRG9QCkloY0ttMDFyYWR0TzV5a2QvNXJKS1RsdTFvdDVHUXNOdTRQN05HZW0yblc2ZHVQRG9SVFF6V3Z6NEV4SDFobXUKWFgrU3hWYU1xeFkycExaWkRWdUpZSEFueEx3L2llSXdsaVo1bzdaNkVBYTZPa25QR1dwUkdPYlc2TEcvcjNldgpDQmNwZ3RETzArU0NTTE9FSDk2cWtSQmlBdjVleTNDeUxrT0hhbEFlVFlIUkxDaUFIc0kzOGNLd0twNG1vSUJwCmtNdU5vUnJmS2JBS0V2N3JMYml2aTRQdk50eldZS1crN1pXckFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRYZmdJbU9zRnVQdStZMDdBLwo4MU1mS2NKM2N6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFmckhwcENCRDV4bUF2UllBQXdvYVlkN0piV1BsCnJJVnMwOEFhUlEvVlJKUm9wMkNESGtxWEhZU3M3M0pzYjNTVXJ5b3R2cnVwNFdvb2FkbHV3WTJhUGVrTzNxcE8KNzVPUktiVGwvaTd5eVVpcVhIUWFoT0VzVFBXVkhVNHBLcWZCNUNwRWFibzFyOXlTa0liZmlvU3M2VWxEaGY2TgpyME1TNWlmMlRuSHVzS2s2V0lBdjJUNUJ1SVpmeWhNN2JESFBJWmhSK0R6c0wwdEtXWWVoS1VGbWh3RFB6QnBxCmRRamRwdlQ3WEtOTzRmVEU4TkRLbVcxQ01aMjI4eG9rYThjR29vK0VhcWR2bHJFMDhzT0t5OFhITjErYjNXK2cKYTJBcC9QOTJPeHphMjZtYTE0UDIvU3dJZXVaam1NNUdtdXNWV24xOFJxMlZ4U25ZajRlWUJWUnNLdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://c52f48e5-985c-46be-8d16-385677804a88.k8s.ondigitalocean.com
  name: do-fra1-k8s-1-20-2-do-0-fra1-1617268555333
contexts:
- context:
    cluster: do-fra1-k8s-1-20-2-do-0-fra1-1617268555333
    user: do-fra1-k8s-1-20-2-do-0-fra1-1617268555333-admin
  name: do-fra1-k8s-1-20-2-do-0-fra1-1617268555333
current-context: do-fra1-k8s-1-20-2-do-0-fra1-1617268555333
kind: Config
preferences: {}
users:
- name: do-fra1-k8s-1-20-2-do-0-fra1-1617268555333-admin
  user:
    token: 788072d44da50a3449106e660ad0ab4625e8ce0b303661421c71c0321827406e
